<?php

return [
    'default' => 'EUR',
    'available' => ['EUR', 'USD', 'GBP', 'TND', 'MAD', 'EGP', 'KES', 'CHF', 'CAD', 'AUD', 'NZD', 'CNY', 'SGD', 'HKD', 'MXN', 'XPF'],

    'symbols' => [
        'EUR' => '€',
        'USD' => '$',
        'GBP' => '£',
        'TND' => 'TND ',
        'MAD' => 'MAD ',
        'EGP' => 'EGP ',
        'KES' => 'KSh ',
        'CHF' => 'CHF ',
        'CAD' => 'C$',
        'AUD' => 'A$',
        'NZD' => 'NZ$',
        'CNY' => '¥',
        'SGD' => 'S$',
        'HKD' => 'HK$',
        'MXN' => 'MX$',
        'XPF' => 'F',
    ],

    'names' => [
        'EUR' => 'Euro',
        'USD' => 'US Dollar',
        'GBP' => 'Pound Sterling',
        'TND' => 'Tunisian Dinar',
        'MAD' => 'Moroccan Dirham',
        'EGP' => 'Egyptian Pound',
        'KES' => 'Kenyan Shilling',
        'CHF' => 'Swiss Franc',
        'CAD' => 'Canadian Dollar',
        'AUD' => 'Australian Dollar',
        'NZD' => 'New Zealand Dollar',
        'CNY' => 'Chinese Yuan',
        'SGD' => 'Singapore Dollar',
        'HKD' => 'Hong Kong Dollar',
        'MXN' => 'Mexican Peso',
        'XPF' => 'CFP Franc',
    ],

    'rates' => [
        'EUR' => 1.0,
        'USD' => 1.08,
        'GBP' => 0.85,
        'TND' => 3.38,
        'MAD' => 10.75,
        'EGP' => 33.50,
        'KES' => 140.0,
        'CHF' => 0.96,
        'CAD' => 1.48,
        'AUD' => 1.63,
        'NZD' => 1.77,
        'CNY' => 7.82,
        'SGD' => 1.44,
        'HKD' => 8.44,
        'MXN' => 18.50,
        'XPF' => 119.33,
    ],
];
